### ISSUE TITLE
Contour lines are not rendered with the Hiking style

### ISSUE THREAD

**Issue by ghislainv** [OsmAnd-Rendering/.github#3]
Contour lines are not rendered with the Hiking style while they are rendered with the Topo style.

**Comment by bobeeeze** [comment]
Yes they are rendered with hiking style
![IMG_20230704_115943](https://github.com/OsmAnd-Rendering/.github/assets/59626956/3dedf787-8dc3-4e5d-81d7-19c058a52b22)
